# Generated by Django 4.1.3 on 2022-11-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=154)),
                ('email', models.CharField(default='', max_length=74)),
                ('text', models.TextField()),
            ],
        ),
    ]
